apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - frontend-deployment.yaml

images:
  - name: 1234567890.dkr.ecr.us-east-1.amazonaws.com/mi-backend
    newTag: latest
  - name: 1234567890.dkr.ecr.us-east-1.amazonaws.com/mi-frontend
    newTag: latest