apiVersion: v1 
kind: ServiceAccount
metadata:
  name: service-account-orchestra-backend
  namespace: orchestra-namespace
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::622370466117:role/kubernetes-oidc-role"

---

apiVersion: v1 
kind: ServiceAccount
metadata:
  name: service-account-orchestra-frontend
  namespace: orchestra-namespace
  